### ISSUE TITLE
slackard.py:278: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6

### ISSUE THREAD

**Issue by k001** [aelse/slackard#6]
slackard.py:278: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  print('Unhandled exception: {}'.format(e.message))
Unhandled exception: user_is_bot

**Comment by k001** [comment]
I'm using
-> python -V
Python 2.7.8

**Comment by aelse** [comment]
Thanks for the report. Slackard's exceptions already inherit from Exception. I would guess that the deprecation warning is due to exception handling in the 'slacker' module slackard uses, but that also inherits from Exception as far back as I've looked.

As for why it's generating the user_is_bot exception, the error is generated when a slack api method is called by a bot user that bot's aren't allowed to call. eg https://api.slack.com/methods/chat.postMessage but i don't know what other methods also generate this.

Do you have any custom plugins loaded? If yes, do any inherit BaseException? Do they use just bot.speak or bot.topic? Maybe that's the culprit...
